services:
  minecraft:
    build: .
    container_name: minecraft
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - ./server:/minecraft
